name: Test Launcher
on:
  workflow-dispatch:

jobs:
  upload:
    name: Build ChimeraOS UNSTABLE image
    uses: ./.github/workflows/build-system-image.yml
    with:
      unrelated_input: "test-upload"
    secrets:
      RCLONE_ACCESS_KEY_ID: ${{ secrets.RCLONE_ACCESS_KEY_ID }}
      RCLONE_SECRET_ACCESS_KEY: ${{ secrets.RCLONE_SECRET_ACCESS_KEY }}
      RCLONE_ENDPOINT: ${{ secrets.RCLONE_ENDPOINT }}